apiVersion: v1
kind: Secret
metadata:
  name: hello-world-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <git-repo-1>
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-deploy-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: <git-repo-2>
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: <gitlab-base-url>
  password: <password>
  username: <username>
