apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  dnsNames:
    - harbor.<domain>
    - harbor-notary.<domain>
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: harbor-letsencrypt-cert
